### ISSUE TITLE
make update aborts: [touch-dbs] Segmentation fault

### ISSUE THREAD

**Issue by ghost** [jeffWelling/moviedb#1]
Hello all,

hopefully I am not the only one who still uses this piece of software. I run on Linux Mint Debian Edition 201403 AMD64, gcc version 4.8.2, libc6 2.17 and moviedb 3.24.

I went successfully through "make compile && make installbin".

When I run "make update" then I get a lot of warnings like this: "titles.key contains 2 identical movies (The Secret (1990))" ending with the error:

/home/patrick/imdb/moviedb-3.24/etc/mkdb  -dist
Adding Distributor List...
mkdb: too many titles -- increase MAXTITLES
make[3]: **\* [distributors.data] Error 255
make[3]: Leaving directory `/home/patrick/imdb/moviedb-3.24/dbs'
/home/patrick/imdb/moviedb-3.24/etc/mkdb  -create
make[2]: *** [touch-dbs] Segmentation fault
make[2]: Leaving directory`/home/patrick/imdb/moviedb-3.24/dbs'
make[1]: **\* [do-databases] Error 2
make[1]: Leaving directory `/home/patrick/imdb/moviedb-3.24'
make: **\* [databases] Error 2

**Comment by jeffWelling** [comment]
I've increased MAXTITLES which looks like the problem, try it again now and let me know if it's still not working?

**Comment by ghost** [comment]
[...]
Adding Distributor List...
mkdb: too many titles -- increase MAXTITLES
make[3]: **\* [distributors.data] Error 255
make[3]: Leaving directory `/home/patrick/imdb/moviedb-master/dbs'
/home/patrick/imdb/moviedb-master/etc/mkdb  -create
make[2]: *** [touch-dbs] Segmentation fault
make[2]: Leaving directory`/home/patrick/imdb/moviedb-master/dbs'
make[1]: **\* [do-databases] Error 2
make[1]: Leaving directory `/home/patrick/imdb/moviedb-master'
make: **\* [databases] Error 2
